RE/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('default-admin/', admin.site.urls),
                  path('admin/', include('rental_exchange.urls_admin')),
                  path('', include('rental_exchange.urls')),
                  path('', include('users.urls')),
                  path('admin/', include('users.urls_admin')),
                  path('djrichtextfield/', include('djrichtextfield.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rental_exchange/urls.py
from django.urls import path
from rental_exchange import views
urlpatterns = [
    path('', views.home_view, name='home'),
    path('about/', views.about_view, name='about'),
    path('blog/', views.blog_view, name='blog'),
    path('blog/details/<int:pk>/', views.BlogDetailView.as_view(), name='blog-details'),
    path('customer/profile/<int:pk>/', views.ProfileDetailView.as_view(), name='customer-profile'),
    path('customer/booking/list/', views.BookingListView.as_view(), name='customer-bookings'),
    # path('customer/booking/create/<int:car_id>/', views.CarBookingBSModalCreateView.as_view(), name='customer-booking-create-bsm'),
    # path('blog-detail', views.blog_detail_view, name='blog-detail'),
    path('pricing', views.pricing_view, name='pricing'),
    path('contact', views.contact_view, name='contact'),
    path('car/', views.CarListView.as_view(), name='car'),
    # path('car/<id>/', views.car_detail_view, name='car-detail'),
    # path('car-detail', views.car_detail_view, name='car-detail'),
    path('car/details/<int:pk>/', views.CarDetailView.as_view(), name='car-detail'),
    path('contact/create/', views.ContactCreate.as_view(), name='contact_create'),
    path('request/car/registration/', views.home_view, name='car-registration-request'),
]

rental_exchange/models.py
import datetime

from django.conf import settings
from django.urls import reverse
from djrichtextfield.models import RichTextField

from users.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.
from django_countries.fields import CountryField
from djmoney.models.fields import MoneyField


class Car(models.Model):
    TRANSMISSIONS = [
        ('Manual', 'Manual'),
        ('Automatic', 'Automatic')
    ]
    FUELS = [
        ('Gasoline', 'Gasoline'),
        ('Diesel', 'Diesel'),
        ('Liquefied Petroleum', 'Liquefied Petroleum'),
        ('Compressed Natural Gas', 'Compressed Natural Gas'),
        ('Ethanol', 'Ethanol'),
        ('Bio-diesel', 'Bio-diesel')
    ]
    PRICE_VARIATIONS = [
        ('Month', 'Month')
    ]
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    name = models.CharField(max_length=255, blank=False, null=False)
    brand = models.ForeignKey('Brand', on_delete=models.SET_NULL, blank=False, null=True)
    model_no = models.CharField(max_length=50, blank=False, null=False)
    model_year = models.IntegerField(
        validators=[MinValueValidator(1984), MaxValueValidator(datetime.date.today().year)], blank=False)
    license_no = models.CharField(max_length=100, null=True, blank=True)
    mileage = models.IntegerField(default=0, blank=False, null=False)
    transmission = models.CharField(max_length=20, choices=TRANSMISSIONS, blank=False, null=False)
    seats = models.IntegerField(default=0, blank=False, null=False)
    luggage = models.IntegerField(default=0, blank=False, null=False)
    fuels = models.ManyToManyField('Fuel', blank=True)
    description = models.TextField(blank=True, null=True)
    rental_price = MoneyField(max_digits=14, decimal_places=2, default=0.00, default_currency='USD', blank=False,
                              null=False)
    price_variable = models.CharField(max_length=20, choices=PRICE_VARIATIONS, default='Month', blank=False, null=False)
    features = models.ManyToManyField('Feature', blank=True)
    is_published = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    image = models.ImageField(upload_to='rental_exchange/car_images', null=True, blank=True)
    fitness_test = models.CharField(max_length=20, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], null=True, blank=True)
    agreement_paper = models.FileField(upload_to='rental_exchange/agreement_papers/', null=True, blank=True)
    tags = models.CharField(max_length=512, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+")

    def __str__(self):
        return self.name

    class Meta:
        db_table = "cars"
        verbose_name_plural = "Cars".upper()
        ordering = ("created_at",)
        unique_together = ('name', 'model_no', 'model_year')

    def get_absolute_url(self):
        # return f"car/{self.id}/"
        return reverse('car-detail', args=[self.id])


class Brand(models.Model):
    name = models.CharField(max_length=50, unique=True, blank=False, null=False)
    description = models.TextField(blank=True, null=True)
    logo = models.ImageField(upload_to='rental_exchange/brand_images', null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+")

    def __str__(self):
        return self.name

    class Meta:
        db_table = "brands"
        verbose_name_plural = "Brands".upper()
        ordering = ("name",)


class Feature(models.Model):
    title = models.CharField(max_length=255, unique=True, blank=False, null=False)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+")

    def __str__(self):
        return self.title

    class Meta:
        db_table = "features"
        verbose_name_plural = "Features".upper()
        ordering = ("title",)


class Fuel(models.Model):
    title = models.CharField(max_length=255, unique=True, blank=False, null=False)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+")

    def __str__(self):
        return self.title

    class Meta:
        db_table = "fuels"
        verbose_name_plural = "Fuels".upper()
        ordering = ("title",)


# class Owner(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     phone = models.CharField(max_length=20, blank=False, null=False)
#     country = CountryField(blank=False, null=False)
#     city = models.CharField(max_length=100, blank=False, null=False)
#     address = models.CharField(max_length=255, blank=False, null=False)
#     image = models.ImageField(upload_to='rental_exchange/owner_images', null=True, blank=True)
#     created_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+")
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#     updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+")
#
#     def __str__(self):
#         return self.user
#
#     class Meta:
#         db_table = "owners"
#         verbose_name_plural = "Owners".upper()
#         ordering = ("id",)


# class Customer(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     phone = models.CharField(max_length=20, blank=False, null=False)
#     country = CountryField(blank=False, null=False)
#     city = models.CharField(max_length=100, blank=False, null=False)
#     address = models.CharField(max_length=255, blank=False, null=False)
#     image = models.ImageField(upload_to='rental_exchange/customer_images', null=True, blank=True)
#     created_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+")
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#     updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+")
#
#     def __str__(self):
#         return self.user
#
#     class Meta:
#         db_table = "customers"
#         verbose_name_plural = "Customers".upper()


class Blog(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    short_description = models.TextField(blank=False, null=False)
    description = models.TextField(blank=False, null=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True,
                                   related_name="+")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True,
                                   related_name="+")

    def __str__(self):
        return self.title

    class Meta:
        db_table = "blogs"
        verbose_name_plural = "Blogs".upper()
        ordering = ("-created_at",)


class Comment(models.Model):
    comment = models.TextField(blank=False, null=False)
    blog = models.ForeignKey('Blog', on_delete=models.CASCADE, blank=True, null=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True,
                                   related_name="+")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True,
                                   related_name="+")

    def __str__(self):
        return self.comment

    class Meta:
        db_table = "comments"
        verbose_name_plural = "Comments".upper()
        ordering = ("created_at",)


class Contact(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    email = models.EmailField(max_length=255, blank=False, null=False)
    subject = models.CharField(max_length=255, blank=False, null=False)
    message = models.TextField(blank=False, null=False)
    is_seen = models.BooleanField(default=False)
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="+")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email

    class Meta:
        db_table = "contacts"
        verbose_name_plural = "Contacts".upper()
        ordering = ("created_at",)


class System(models.Model):
    site_title = models.CharField(max_length=255, default='Rental Exchange', blank=False, null=False)

rental_exchange/forms.py
from datetime import date

from bootstrap_modal_forms.forms import BSModalModelForm
from django import forms
from django.forms import ModelForm, CheckboxSelectMultiple

from rental_exchange.models import Car, System, Contact, Feature, Fuel, Brand, Blog, CarRegistrationRequest, CarBooking, \
    Comment
from users.forms import UserCreationForm
from users.models import User


class CarForm(ModelForm):
    # features = forms.ModelMultipleChoiceField(
    #     queryset=Feature.objects.all(),
    #     widget=forms.CheckboxSelectMultiple,
    #     required=True)
    owner = forms.ModelChoiceField(queryset=User.objects.filter(user_type='CarOwner'))

    class Meta:
        model = Car
        widgets = {
            'fuels': CheckboxSelectMultiple(),
            'features': CheckboxSelectMultiple(),
        }
        fields = '__all__'


class SystemForm(forms.ModelForm):
    # email_from_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = System
        widgets = {
            'email_from_password': forms.PasswordInput(),
        }
        fields = '__all__'


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
        exclude = ['customer', 'is_seen']


class CarRegistrationRequestForm(forms.ModelForm):
    class Meta:
        model = CarRegistrationRequest
        fields = '__all__'
        exclude = ['is_seen']


# class CustomerRegistrationForm(UserCreationForm.Meta):
#     class Meta(UserCreationForm.Meta):
#         model = Customer
#         # I've tried both of these 'fields' declaration, result is the same
#         # fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
#         fields = UserCreationForm.Meta.fields
#         exclude = ['user', 'created_by', 'updated_by']


# class CustomerRegistrationForm(forms.ModelForm):
#     class Meta:
#         model = Customer
#         # I've tried both of these 'fields' declaration, result is the same
#         # fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
#         fields = '__all__'
#         exclude = ['user', 'created_by', 'updated_by']

class FuelModelFormBS(BSModalModelForm):
    class Meta:
        model = Fuel
        fields = ['title', 'description']


class FeatureModelFormBS(BSModalModelForm):
    class Meta:
        model = Feature
        fields = ['title', 'description']


class BrandModelFormBS(BSModalModelForm):
    class Meta:
        model = Brand
        fields = ['name', 'description', 'logo']


class BlogModelFormBS(BSModalModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'short_description', 'description']


class CreateBookingBSModalModelForm(BSModalModelForm):
    class Meta:
        model = CarBooking
        fields = '__all__'
        widgets = {
            'start_date': forms.DateInput(format=('%m/%d/%Y'),
                                             attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                                    'type': 'date', 'min': date.today()}),
        }


class CreateBookingForm(forms.ModelForm):
    class Meta:
        model = CarBooking
        fields = '__all__'
        widgets = {
            'start_date': forms.DateInput(format=('%m/%d/%Y'),
                                             attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                                    'type': 'date', 'min': date.today()}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

templates/rental_exchange/containers/blog-single.html
{% extends 'rental_exchange/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<section class="hero-wrap hero-wrap-2 js-fullheight"
         style="background-image: url({% static 'rental_exchange/images/bg_2.jpg' %});"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start">
            <div class="col-md-9 ftco-animate pb-5">
                <p class="breadcrumbs"><span class="mr-2"><a href="index-2.html">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="blog.html">Blog <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i
                        class="ion-ios-arrow-forward"></i></span></p>
                <h1 class="mb-3 bread">Read our blog</h1>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section ftco-degree-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-8 order-md-last ftco-animate">
                <h2 class="mb-3 text-capitalize">{{ blog.title }}</h2>
                <div class="meta">
                    <div><a href="#"><i class="fas fa-calendar"></i> {% firstof blog.updated_at blog.created_at %} </a> <a href="#"> <i class="fas fa-user"></i> {% firstof blog.updated_by blog.created_by %}</a></div>
                </div>
                <p>{{ blog.description }}</p>
                <!--                <p>-->
                <!--                    <img src="images/image_7.html" alt="" class="img-fluid">-->
                <!--                </p>-->
                <!--                <p>Molestiae cupiditate inventore animi, maxime sapiente optio, illo est nemo veritatis repellat sunt-->
                <!--                    doloribus nesciunt! Minima laborum magni reiciendis qui voluptate quisquam voluptatem soluta illo-->
                <!--                    eum ullam incidunt rem assumenda eveniet eaque sequi deleniti tenetur dolore amet fugit perspiciatis-->
                <!--                    ipsa, odit. Nesciunt dolor minima esse vero ut ea, repudiandae suscipit!</p>-->
                <!--                <h2 class="mb-3 mt-5">#2. Creative WordPress Themes</h2>-->
                <!--                <p>Temporibus ad error suscipit exercitationem hic molestiae totam obcaecati rerum, eius aut, in.-->
                <!--                    Exercitationem atque quidem tempora maiores ex architecto voluptatum aut officia doloremque. Error-->
                <!--                    dolore voluptas, omnis molestias odio dignissimos culpa ex earum nisi consequatur quos odit quasi-->
                <!--                    repellat qui officiis reiciendis incidunt hic non? Debitis commodi aut, adipisci.</p>-->
                <!--                <p>-->
                <!--                    <img src="images/image_8.html" alt="" class="img-fluid">-->
                <!--                </p>-->
                <!--                <p>Quisquam esse aliquam fuga distinctio, quidem delectus veritatis reiciendis. Nihil explicabo quod,-->
                <!--                    est eos ipsum. Unde aut non tenetur tempore, nisi culpa voluptate maiores officiis quis vel ab-->
                <!--                    consectetur suscipit veritatis nulla quos quia aspernatur perferendis, libero sint. Error, velit,-->
                <!--                    porro. Deserunt minus, quibusdam iste enim veniam, modi rem maiores.</p>-->
                <!--                <p>Odit voluptatibus, eveniet vel nihil cum ullam dolores laborum, quo velit commodi rerum eum quidem-->
                <!--                    pariatur! Quia fuga iste tenetur, ipsa vel nisi in dolorum consequatur, veritatis porro explicabo-->
                <!--                    soluta commodi libero voluptatem similique id quidem? Blanditiis voluptates aperiam non magni.-->
                <!--                    Reprehenderit nobis odit inventore, quia laboriosam harum excepturi ea.</p>-->
                <!--                <p>Adipisci vero culpa, eius nobis soluta. Dolore, maxime ullam ipsam quidem, dolor distinctio similique-->
                <!--                    asperiores voluptas enim, exercitationem ratione aut adipisci modi quod quibusdam iusto, voluptates-->
                <!--                    beatae iure nemo itaque laborum. Consequuntur et pariatur totam fuga eligendi vero dolorum-->
                <!--                    provident. Voluptatibus, veritatis. Beatae numquam nam ab voluptatibus culpa, tenetur-->
                <!--                    recusandae!</p>-->
                <!--                <p>Voluptas dolores dignissimos dolorum temporibus, autem aliquam ducimus at officia adipisci quasi nemo-->
                <!--                    a perspiciatis provident magni laboriosam repudiandae iure iusto commodi debitis est blanditiis-->
                <!--                    alias laborum sint dolore. Dolores, iure, reprehenderit. Error provident, pariatur cupiditate soluta-->
                <!--                    doloremque aut ratione. Harum voluptates mollitia illo minus praesentium, rerum ipsa debitis,-->
                <!--                    inventore?</p>-->
                <!--                <div class="tag-widget post-tag-container mb-5 mt-5">-->
                <!--                    <div class="tagcloud">-->
                <!--                        <a href="#" class="tag-cloud-link">Life</a>-->
                <!--                        <a href="#" class="tag-cloud-link">Sport</a>-->
                <!--                        <a href="#" class="tag-cloud-link">Tech</a>-->
                <!--                        <a href="#" class="tag-cloud-link">Travel</a>-->
                <!--                    </div>-->
                <!--                </div>-->
                <!--                <div class="about-author d-flex p-4 bg-light">-->
                <!--                    <div class="bio mr-5">-->
                <!--                        <img src="images/person_1.jpg" alt="Image placeholder" class="img-fluid mb-4">-->
                <!--                    </div>-->
                <!--                    <div class="desc">-->
                <!--                        <h3>George Washington</h3>-->
                <!--                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem-->
                <!--                            necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente-->
                <!--                            consectetur similique, inventore eos fugit cupiditate numquam!</p>-->
                <!--                    </div>-->
                <!--                </div>-->
                <div class="pt-3 mt-3">
                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form method="post" action="." class="p-5 bg-light">
                            {% csrf_token %}
                            {{ comment_form.blog.as_hidden }}
                            {{ comment_form.created_by.as_hidden }}
                            <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
                                {% for error in form.non_field_errors %}
                                {{ error }}
                                {% endfor %}
                            </div>
                            <div class="form-group">
                                {% render_field comment_form.comment class="form-control" cols="30" rows="5" placeholder="Leave a comment" %}
                                <div class="{% if comment_form.comment.errors %} invalid{% endif %}">
                                    {% for error in comment_form.comment.errors %}
                                    <p class="help-block">{{ error }}</p>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
                <div class="pt-3 mt-3">
                    <h3 class="mb-5">{{ comment_list|length }} {% if comment_list|length < 2 %}Comment{% else %}Comments{% endif %}</h3>
                    <ul class="comment-list">
                        {% for comment in comment_list %}
                        <li class="comment">
                            <div class="vcard bio">
                                <img src="{% if comment.created_by.image %}{{ comment.created_by.image.url }}{% endif %}" alt="Image">
                            </div>
                            <div class="comment-body">
                                <h3>{{ comment.created_by.first_name }} {{ comment.created_by.last_name }}</h3>
                                <div class="meta">{{ comment.created_at }}</div>
                                <p>{{ comment.comment }}</p>
                                <p><a href="#" class="reply">Reply</a></p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md-4 sidebar ftco-animate">
<!--                <div class="sidebar-box">-->
<!--                    <form action="#" class="search-form">-->
<!--                        <div class="form-group">-->
<!--                            <span class="icon icon-search"></span>-->
<!--                            <input type="text" class="form-control" placeholder="Type a keyword and hit enter">-->
<!--                        </div>-->
<!--                    </form>-->
<!--                </div>-->
<!--                <div class="sidebar-box ftco-animate">-->
<!--                    <div class="categories">-->
<!--                        <h3>Categories</h3>-->
<!--                        <li><a href="#">Jobs <span>(12)</span></a></li>-->
<!--                        <li><a href="#">Visual Assistant <span>(22)</span></a></li>-->
<!--                        <li><a href="#">Coffee <span>(37)</span></a></li>-->
<!--                        <li><a href="#">Drinks <span>(42)</span></a></li>-->
<!--                        <li><a href="#">Foods <span>(14)</span></a></li>-->
<!--                        <li><a href="#">Travel <span>(140)</span></a></li>-->
<!--                    </div>-->
<!--                </div>-->
                <div class="sidebar-box ftco-animate">
                    <h3>Recent Blog</h3>
                    {% for rbl in recent_blog_list %}
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url(images/image_1.jpg);" alt="Image"></a>
                        <div class="text">
                            <h3 class="heading"><a href="{% url 'blog-details' rbl.pk %}">{{ rbl.title }}</a></h3>
                            <div class="meta">
                                <div><a href="#"><i class="fas fa-calendar"></i> {% firstof blog.updated_at blog.created_at %}</a></div>
                                <div><a href="#"><i class="fas fa-user"></i> {% firstof blog.updated_by blog.created_by %}</a></div>
<!--                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>-->
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
<!--                <div class="sidebar-box ftco-animate">-->
<!--                    <h3>Tag Cloud</h3>-->
<!--                    <div class="tagcloud">-->
<!--                        <a href="#" class="tag-cloud-link">dish</a>-->
<!--                        <a href="#" class="tag-cloud-link">menu</a>-->
<!--                        <a href="#" class="tag-cloud-link">food</a>-->
<!--                        <a href="#" class="tag-cloud-link">sweet</a>-->
<!--                        <a href="#" class="tag-cloud-link">tasty</a>-->
<!--                        <a href="#" class="tag-cloud-link">delicious</a>-->
<!--                        <a href="#" class="tag-cloud-link">desserts</a>-->
<!--                        <a href="#" class="tag-cloud-link">drinks</a>-->
<!--                    </div>-->
<!--                </div>-->
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/rental_exchange/containers/blog.html
{% extends 'rental_exchange/base.html' %}
{% load static %}
{% block content %}
<section class="hero-wrap hero-wrap-2 js-fullheight"
         style="background-image: url({% static 'rental_exchange/images/bg_2.jpg' %});"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start">
            <div class="col-md-9 ftco-animate pb-5">
                <p class="breadcrumbs"><span class="mr-2"><a href="index-2.html">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>Blog <i
                        class="ion-ios-arrow-forward"></i></span></p>
                <h1 class="mb-3 bread">Read our blog</h1>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section">
    <div class="container">
        <div class="row d-flex justify-content-center">
            {% if blog_list %}
            {% for blog in blog_list %}
            <div class="col-md-10 text-center d-flex ftco-animate">
                <div class="blog-entry justify-content-end">
<!--                    <a href="blog-single.html" class="block-20 img"-->
<!--                       style="background-image: url('images/image_1.jpg');">-->
<!--                    </a>-->
                    <div class="text pt-4">
                        <div class="meta mb-3">
                            <div><a href="{% url 'blog-details' blog.pk %}">{% firstof blog.updated_at blog.created_at %}</a></div>
<!--                            <div><a href="#">Admin</a></div>-->
<!--                            <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>-->
                        </div>
                        <h3 class="heading mt-2 text-capitalize"><a href="{% url 'blog-details' blog.pk %}">{{ blog.title }}</a></h3>
                        <p>{{ blog.description|slice:":250" }} {% if blog.description|length > 250 %}...{% endif %}</p>
                        <p><a href="{% url 'blog-details' blog.pk %}" class="btn-custom">Continue <span
                                class="icon-long-arrow-right"></span></a></p>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="col-md-10 text-center d-flex ftco-animate">
                <div class="blog-entry justify-content-end">
                    <div class="text pt-4">
                        <h3 class="heading mt-2">There are no post available!!!</h3>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">
                    <ul>
                        <li><a href="#">&lt;</a></li>
                        <li class="active"><span>1</span></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">&gt;</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}